include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude: 
    - lib/**/*.g.dart
linter:
  rules:
    sort_pub_dependencies: false
    use_setters_to_change_properties: false
    avoid_catches_without_on_clauses: false